version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=coursewagon
      - JWT_SECRET_KEY=your-secret-key
      - API_KEY=${API_KEY}
      - DEBUG=true
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/main.go

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coursewagon
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: