name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

env:
  PROJECT_ID: mitra-348d9
  SERVICE_NAME: coursewagon-api
  REGION: us-central1
  ARTIFACT_REGISTRY_REPO: coursewagon-repo
  IMAGE_NAME: coursewagon-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if it's a push to main OR a merged pull request to main
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check for Python server changes
      id: changes
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "Manual trigger - deploying"
          echo "deploy=true" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "push" ]; then
          if git diff --name-only HEAD~1 HEAD | grep -q "^python-server/"; then
            echo "Python server changes detected - deploying"
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "No Python server changes - skipping deployment"
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "PR merge - deploying"
          echo "deploy=true" >> $GITHUB_OUTPUT
        fi

    - name: Setup Google Cloud SDK
      if: steps.changes.outputs.deploy == 'true'
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      if: steps.changes.outputs.deploy == 'true'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Build and Push with Cloud Build
      if: steps.changes.outputs.deploy == 'true'
      run: |
        cd python-server
        # Build and push image using Cloud Build with substitutions
        gcloud builds submit \
          --tag $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO/$IMAGE_NAME:$GITHUB_SHA \
          --tag $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO/$IMAGE_NAME:latest \
          --timeout=20m \
          --machine-type=e2-highcpu-8 \
          --async \
          .
        
        # Wait for the build to complete and check status
        echo "Waiting for build to complete..."
        sleep 60
        
        # Get the latest build status
        BUILD_STATUS=$(gcloud builds list --limit=1 --format="value(status)")
        echo "Build status: $BUILD_STATUS"
        
        if [ "$BUILD_STATUS" != "SUCCESS" ]; then
          echo "Build failed with status: $BUILD_STATUS"
          exit 1
        fi

    - name: Deploy to Cloud Run
      if: steps.changes.outputs.deploy == 'true'
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image=$REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO/$IMAGE_NAME:$GITHUB_SHA \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated \
          --memory=2Gi \
          --cpu=2 \
          --min-instances=0 \
          --max-instances=10 \
          --port=8000 \
          --timeout=3600 \
          --set-secrets=/app/gcs-service-account.json=COURSEWAGON-GCS-SERVICE-ACCOUNT:latest \
          --set-secrets=/app/firebase-admin-sdk.json=COURSEWAGON-FIREBASE-ADMIN-SDK:latest \
          --set-env-vars="GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-service-account.json" \
          --set-env-vars="FIREBASE_ADMIN_SDK_PATH=/app/firebase-admin-sdk.json" \
          --update-secrets=COURSEWAGON-SECRET-KEY=COURSEWAGON-SECRET-KEY:latest \
          --update-secrets=COURSEWAGON-MYSQL-HOST=COURSEWAGON-MYSQL-HOST:latest \
          --update-secrets=COURSEWAGON-MYSQL-USER=COURSEWAGON-MYSQL-USER:latest \
          --update-secrets=COURSEWAGON-MYSQL-PASSWORD=COURSEWAGON-MYSQL-PASSWORD:latest \
          --update-secrets=COURSEWAGON-MYSQL-DATABASE=COURSEWAGON-MYSQL-DATABASE:latest \
          --update-secrets=COURSEWAGON-JWT-SECRET-KEY=COURSEWAGON-JWT-SECRET-KEY:latest \
          --update-secrets=COURSEWAGON-JWT-ALGORITHM=COURSEWAGON-JWT-ALGORITHM:latest \
          --update-secrets=COURSEWAGON-ACCESS-TOKEN-EXPIRE-MINUTES=COURSEWAGON-ACCESS-TOKEN-EXPIRE-MINUTES:latest \
          --update-secrets=COURSEWAGON-MAIL-USERNAME=COURSEWAGON-MAIL-USERNAME:latest \
          --update-secrets=COURSEWAGON-MAIL-PASSWORD=COURSEWAGON-MAIL-PASSWORD:latest \
          --update-secrets=COURSEWAGON-MAIL-FROM=COURSEWAGON-MAIL-FROM:latest \
          --update-secrets=COURSEWAGON-MAIL-PORT=COURSEWAGON-MAIL-PORT:latest \
          --update-secrets=COURSEWAGON-MAIL-SERVER=COURSEWAGON-MAIL-SERVER:latest \
          --update-secrets=COURSEWAGON-MAIL-STARTTLS=COURSEWAGON-MAIL-STARTTLS:latest \
          --update-secrets=COURSEWAGON-MAIL-SSL-TLS=COURSEWAGON-MAIL-SSL-TLS:latest \
          --update-secrets=COURSEWAGON-USE-CREDENTIALS=COURSEWAGON-USE-CREDENTIALS:latest \
          --update-secrets=COURSEWAGON-VALIDATE-CERTS=COURSEWAGON-VALIDATE-CERTS:latest \
          --update-secrets=COURSEWAGON-AZURE-STORAGE-ACCOUNT-NAME=COURSEWAGON-AZURE-STORAGE-ACCOUNT-NAME:latest \
          --update-secrets=COURSEWAGON-AZURE-STORAGE-ACCOUNT-KEY=COURSEWAGON-AZURE-STORAGE-ACCOUNT-KEY:latest \
          --update-secrets=COURSEWAGON-AZURE-STORAGE-CONNECTION-STRING=COURSEWAGON-AZURE-STORAGE-CONNECTION-STRING:latest \
          --update-secrets=COURSEWAGON-AZURE-CONTAINER-NAME=COURSEWAGON-AZURE-CONTAINER-NAME:latest \
          --update-secrets=COURSEWAGON-GCS-BUCKET-NAME=COURSEWAGON-GCS-BUCKET-NAME:latest \
          --update-secrets=COURSEWAGON-GCS-PROJECT-ID=COURSEWAGON-GCS-PROJECT-ID:latest \
          --update-secrets=COURSEWAGON-FIREBASE-DATABASE-URL=COURSEWAGON-FIREBASE-DATABASE-URL:latest \
          --update-secrets=COURSEWAGON-FIREBASE-STORAGE-BUCKET=COURSEWAGON-FIREBASE-STORAGE-BUCKET:latest \
          --update-secrets=COURSEWAGON-STORAGE-PROVIDER=COURSEWAGON-STORAGE-PROVIDER:latest \
          --update-secrets=COURSEWAGON-DEBUG=COURSEWAGON-DEBUG:latest \
          --update-secrets=COURSEWAGON-CORS-ORIGINS=COURSEWAGON-CORS-ORIGINS:latest

    - name: Get Cloud Run URL
      if: steps.changes.outputs.deploy == 'true'
      run: |
        URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')
        echo "Service deployed at: $URL"
        
    - name: Health Check
      if: steps.changes.outputs.deploy == 'true'
      run: |
        URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')
        echo "Checking health at: $URL/api/health"
        # Wait a  bit for the service to be ready
        sleep 30
        curl -f "$URL/api/health" || echo "Health check failed, but deployment completed"
