name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'angular-client/**'
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'angular-client/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  ANGULAR_PROJECT_PATH: './angular-client'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only run if it's a push to main OR a merged pull request to main
    if: |
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch')

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.ANGULAR_PROJECT_PATH }}/package-lock.json

    - name: Create environment file
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: |
        # Create production environment file from GitHub secrets
        cat > src/environments/environment.ts << EOF
        export const environment = {
          production: true,
          apiUrl: '${{ secrets.ANGULAR_API_URL }}',
          apiBaseUrl: '${{ secrets.ANGULAR_API_BASE_URL }}',
          courseApiUrl: '${{ secrets.ANGULAR_COURSE_API_URL }}',
          authApiUrl: '${{ secrets.ANGULAR_AUTH_API_URL }}',
          firebase: {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}'
          }
        };
        EOF

    - name: Install dependencies
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm ci

    - name: Run tests
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: Build Angular app
      working-directory: ${{ env.ANGULAR_PROJECT_PATH }}
      run: npm run build -- --configuration production

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
        channelId: live
        entryPoint: ${{ env.ANGULAR_PROJECT_PATH }}

    - name: Test deployed site
      run: |
        sleep 30
        curl --fail "https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app" || \
        curl --fail "https://${{ secrets.FIREBASE_PROJECT_ID }}.firebaseapp.com"
